name: JiraDeployment

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
